### ISSUE TITLE
.2mm thru holes unacceptable to Seeede Studio

### ISSUE THREAD

**Issue by patt896** [smartboxchannel/EFEKTA_E73B_PWS_MODULE#1]
This is from the Seeed Studio Fusion team.

Thanks for your order but there are some problems in your files.

PCB file name: D_1253859_prod.zip

 

Problem Description:

      

When the order was placed, 0.3mm minimum drill hole size was selected, but in the files there appears to be 0.2mm drill holes. If we continue with production with these files, it will cost an additional $100USD. If that is ok, please use the link below to complete payment. Alternatively, we can ignore these holes or enlarge them to 0.3mm, or you could modify the files and send them directly to us.

**Comment by smartboxchannel** [comment]
Changed to 0.3

**Comment by patt896** [comment]
Thx, so much.  Purchased for $15 USD an Amazon.  Hope Author Benefits from Patent:
Aideepen Capacitive Soil Moisture Module, DHT11 Temperature Humidity Sensor 
ESP8266 ESP-32 WiFi Shield with 18650 Battery Holder for Arduino.

**Comment by patt896** [comment]
Hackers delight.  Took two months to sort out syntax inconsistencies between Arduino C++, HTML, CSS,  Google Gauge and Java Script.   Not to mention Zoom capabilities of various browsers under Win 10, Ubuntu and Android.  And side load issues with Google Play Store Apps.
